# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

SPACE_WALLPAPERS = [
  "http://i.imgur.com/cplXyB9.jpg",
  "http://i.imgur.com/zH38b9F.jpg",
  "http://i.imgur.com/hLGH5uk.jpg",
  "http://i.imgur.com/XebDpgg.jpg",
  "http://i.imgur.com/IZXI25D.jpg",
  "http://i.imgur.com/5oKFC99.png",
  "http://i.imgur.com/rP71Q5Q.png",
  "http://i.imgur.com/UiZyRzR.jpg",
  "http://i.imgur.com/My4w4x8.jpg",
  "http://i.imgur.com/ky1DeyK.jpg",
  "http://i.imgur.com/NAJk1Ug.jpg",
  "http://i.imgur.com/f3EkPYd.jpg",
  "http://i.imgur.com/kITTstY.jpg",
  "http://i.imgur.com/h87CV3E.jpg",
  "http://i.imgur.com/E7xIZhR.jpg",
  "http://i.imgur.com/gOV3A9n.jpg",
  "http://i.imgur.com/Sh2MUph.jpg",
  "http://i.imgur.com/4289nyZ.jpg",
  "http://i.imgur.com/ASvfaZz.jpg",
  "http://i.imgur.com/vWIdu7i.jpg",
  "http://i.imgur.com/d4HTHLn.jpg",
  "http://i.imgur.com/FQg4Smh.jpg",
  "http://i.imgur.com/65ux6u5.jpg",
  "http://i.imgur.com/7UXYO2v.jpg",
  "http://i.imgur.com/IQMvO6T.jpg",
  "http://i.imgur.com/L3nJtTp.jpg",
  "http://i.imgur.com/3uVnDXv.jpg",
  "http://i.imgur.com/wjwVSd6.jpg",
  "http://i.imgur.com/bNIjZFI.jpg",
  "http://i.imgur.com/FgnAFbn.jpg",
  "http://i.imgur.com/aep8iYg.jpg",
  "http://i.imgur.com/cRJIxQU.jpg",
  "http://i.imgur.com/rxF4HLf.jpg",
  "http://i.imgur.com/41mUMjv.jpg",
  "http://i.imgur.com/8VtKX7m.jpg",
  "http://i.imgur.com/gtQleoO.jpg",
  "http://i.imgur.com/6SflI8T.jpg",
  "http://i.imgur.com/jZd5CmL.jpg",
  "http://i.imgur.com/ho13B5Y.jpg",
  "http://i.imgur.com/GgimzYF.jpg",
  "http://i.imgur.com/ZDRc3nh.jpg",
  "http://i.imgur.com/cWa31CI.jpg",
  "http://i.imgur.com/5lOpD6q.jpg",
  "http://i.imgur.com/gFqQ0wz.jpg",
  "http://i.imgur.com/Q6lvD2i.jpg",
  "http://i.imgur.com/bHeua0x.jpg",
  "http://i.imgur.com/cqQPcwY.jpg",
  "http://i.imgur.com/r7Aw4Qt.jpg",
  "http://i.imgur.com/NYLVaCL.jpg",
  "http://i.imgur.com/zWBvjHo.jpg",
  "http://i.imgur.com/s5ymPAe.jpg",
  "http://i.imgur.com/DcXdzZD.jpg",
  "http://i.imgur.com/Mya9kCh.jpg",
  "http://i.imgur.com/uPP8LVU.jpg",
  "http://i.imgur.com/gHG2SCQ.jpg",
  "http://i.imgur.com/WNaJ9vb.jpg",
  "http://i.imgur.com/dzBG7Lv.jpg",
  "http://i.imgur.com/v3yJIJt.jpg",
  "http://i.imgur.com/HErJnuC.jpg",
  "http://i.imgur.com/pUTkBEj.jpg",
  "http://i.imgur.com/BPbV1sI.jpg",
  "http://i.imgur.com/MP84GDv.jpg",
  "http://i.imgur.com/FWE7lq9.jpg",
  "http://i.imgur.com/xHRJORX.jpg",
  "http://i.imgur.com/wDK1jJM.jpg",
  "http://i.imgur.com/DrpdDaR.jpg",
  "http://i.imgur.com/gxhZpEQ.jpg",
  "http://i.imgur.com/DovXsb8.jpg",
  "http://i.imgur.com/6YNQ8oo.jpg",
  "http://i.imgur.com/e22ThLd.jpg",
  "http://i.imgur.com/HBPMWY2.jpg",
  "http://i.imgur.com/vkKo1rz.jpg",
  "http://i.imgur.com/lNlxSzK.jpg",
  "http://i.imgur.com/MZ1WPRP.jpg",
  "http://i.imgur.com/lsikHS0.jpg",
  "http://i.imgur.com/3yamfwD.jpg",
  "http://i.imgur.com/dws0ouk.jpg",
  "http://i.imgur.com/1H6JYWH.jpg",
  "http://i.imgur.com/C0FxNge.jpg",
  "http://i.imgur.com/r4ien5x.jpg",
  "http://i.imgur.com/oP8qicG.jpg",
  "http://i.imgur.com/UjO72L2.jpg",
  "http://i.imgur.com/Ocb68tB.jpg",
  "http://i.imgur.com/35Vv9SE.jpg",
  "http://i.imgur.com/zZxwQ9s.jpg",
  "http://i.imgur.com/qP6UM4H.jpg",
  "http://i.imgur.com/AcHIxrZ.jpg",
  "http://i.imgur.com/NvQ5Tq4.jpg",
  "http://i.imgur.com/dEoVbGM.jpg",
  "http://i.imgur.com/zkCf7U7.jpg",
  "http://i.imgur.com/Im0JGyU.jpg"
]

SPACE_WALLPAPERS.shuffle!

User.create(email: "demo@example.com", username: "demo", first_name: "Demo", last_name: "User", password_digest: BCrypt::Password.create("password"))

SPACE_WALLPAPERS.count.times do |index|
  Photo.create(title: Faker::StarWars.planet, description: Faker::StarWars.quote, photo_url: SPACE_WALLPAPERS[index], user_id: 1)
end
